// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu7md7zRTe2a5wDf-D-o8ZwXS8_DFdbbc',
    appId: '1:375718918494:web:339ee87fdd93e8b1d837cf',
    messagingSenderId: '375718918494',
    projectId: 'my-chat-1-51348',
    authDomain: 'my-chat-1-51348.firebaseapp.com',
    storageBucket: 'my-chat-1-51348.appspot.com',
    measurementId: 'G-9ELHXVESJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqV2x_Fl5CtSBuURCeSIN-7MU8TAIvoy8',
    appId: '1:375718918494:android:94797d4e817a3c14d837cf',
    messagingSenderId: '375718918494',
    projectId: 'my-chat-1-51348',
    storageBucket: 'my-chat-1-51348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0bgimGJTfR1zjxiRR82AiXBzzPOs-ho',
    appId: '1:375718918494:ios:47403ea4aed0a525d837cf',
    messagingSenderId: '375718918494',
    projectId: 'my-chat-1-51348',
    storageBucket: 'my-chat-1-51348.appspot.com',
    androidClientId: '375718918494-6kta2jncabncfdr7gtrq6i6phvi5qfmn.apps.googleusercontent.com',
    iosClientId: '375718918494-j9p5cjh85gd3bmtgt10i824vbnpcoi50.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF0bgimGJTfR1zjxiRR82AiXBzzPOs-ho',
    appId: '1:375718918494:ios:47403ea4aed0a525d837cf',
    messagingSenderId: '375718918494',
    projectId: 'my-chat-1-51348',
    storageBucket: 'my-chat-1-51348.appspot.com',
    androidClientId: '375718918494-6kta2jncabncfdr7gtrq6i6phvi5qfmn.apps.googleusercontent.com',
    iosClientId: '375718918494-j9p5cjh85gd3bmtgt10i824vbnpcoi50.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
